#!/bin/sh

EIS="Error: Invalid syntax."
EDZ="Error: Division by zero."

# Usage: `test <in> <out>`.
test() {
	[ "$(./calculator "$1" 2>&1)" != "$2" ] \
		&& echo "Test failed: $1 != $2" \
		&& exit 1
}

test "(((" "$EIS"
test "1/0" "$EDZ"
test "2*2" "4"
test "123()" "$EIS"
test "1*2+3/4" "2"
test "1*(2+3)/4" "1"
test "1/2/3/4" "0"
test "1+3*2/(3-1-2)" "$EDZ"
test "1--" "$EIS"
test "1-*" "$EIS"
test "1-1-*1" "$EIS"
test "--1" "$EIS"
test "11-" "$EIS"
test "()" "$EIS"
test "(-)" "$EIS"
test "" "$EIS"
test ")" "$EIS"
test "1+1)(" "$EIS"
test "1)+(2" "$EIS"
test "(1+2))+(3" "$EIS"
test "123" "123"
test "(123)" "123"
test "((123))" "123"
test "1-23-456-7890" "-8368"
test "(1)-(23)" "-22"
test "(-23)-(-46)" "23"
test "(12/1+5*3)-2" "25"
test " " "$EIS"

echo "Success."
